development:
  adapter: postgresql
  encoding: unicode
  database: rails_trello_dev
  pool: 5
  host: localhost
  username: postgres
  password: gfhjkm123
test:
  adapter: postgresql
  encoding: unicode
  database: rails_trello_test
  pool: 5
  host: localhost
  username: postgres
  password: gfhjkm123
